name: UpperEel_box.wy2003
log_location: /home/ab6361/hydrogen_workspace/hydrogen-emulator-1ts
model_type: resnet # fixed for now
optimizer: adam # fixed for now
loss: mse # fixed for now
n_epochs: 100 # small for testing
batch_size: 8 # small for testing
lr: 0.00001
num_workers: 16
dtype: float32
device: cuda:0
data_def:
  train_data_location: /scratch/network/reedmm/1ts_training/Upper_Eel_box/
  validation_data_location: /scratch/network/reedmm/1ts_training/Upper_Eel_box/
  test_data_location: /scratch/network/reedmm/1ts_training/Upper_Eel_box/
  parameter_list: ['alpha', 'n', 'slope_x', 'slope_y', 'perm_x', 'perm_y' , 'perm_z', 'porosity', 'mannings', 'specific_storage', 'sres' , 'ssat']
  patch_size_x: 64
  patch_size_y: 62
  overlap_x: 0
  overlap_y: 0
  #param_nlayer: [0, 0, 0, 0, 0, 0, 0, 0, 0,0,0]
  param_nlayer: [0, 0, 3, 3, 3, 0, 0, 0, -5] #Number of layers to use for each file in the parameter lis (0= use all, -n = n top layers, +n = n bottom layers)
  n_evaptrans: 4
  shuffle: False
model_def:
  in_channels: 70 # Number of input channels from state_data
  out_channels: 10 # Number of output channels (depth layers)
  kernel_size: 3 # Kernel size for the convolutional layers
  hidden_dim: 128 # Number of filters in the convolutional layers
  depth: 4 # Number of resnet blocks
