name: test
log_location: /home/lc2465/NAIRR/test_training
model_type: resnet # fixed for now
optimizer: adam # fixed for now
loss: mse # fixed for now
n_epochs: 2 # small for testing
batch_size: 4 # small for testing
lr: 0.001
num_workers: 1
device: cpu
data_def:
  data_dir: /home/lc2465/NAIRR/ #Directory that contains the training data run
  run_name: test_box2_conus2_2002WY # name of training data run
  parameter_list: ['slope_x', 'slope_y', 'permeability_x', 'permeability_y' , 'permeability_z', 'porosity', 'pf_flowbarrier', 'mannings', 'specific_storage', 'sres' , 'ssat']  #This is the full parameter list (in_channels=97)
  #parameter_list: ['slope_x', 'slope_y', 'permeability_x', 'mannings']
  patch_size: 16   #Training patch size from within the training domain
  overlap: 4
  scaler_yaml: /home/lc2465/NAIRR/hydrogen-emulator-1ts/emulator-1ts/default_scalers_adjusted.yaml # path to scaler yaml file
  param_nlayer: [0, 0, 0, 0, 0, 0, 0, 0, 0,0,0] #Number of layers to use for each file in the parameter lis (0= use all, -n = n top layers, +n = n bottom layers)
  n_evaptrans: 4 #number of layers to use from the evaptrans files (assumes its from the top down)
model_def:
  in_channels: 97 # Number of input channels from state_data (sum(parameters*param_layer)+n_evaptrans+10)
  out_channels: 10 # Number of output channels (depth layers)
  kernel_size: 3 # Kernel size for the convolutional layers
  depth: 3 # Number of resnet blocks

